language: python
dist: focal
addons:
  apt:
    packages:
      - cmake
      - valgrind
install:
  - pip install -r requirements.txt
script:
  - PYTHONMALLOC=malloc valgrind --show-leak-kinds=definite --log-file=/tmp/valgrind-output python -m pytest -s -vv --valgrind --valgrind-log=/tmp/valgrind-output