language: python
dist: focal
addons:
  apt:
    packages:
      - cmake
      - valgrind
before_install:
  - python -m pip install --upgrade pip
install:
  - xargs -L 1 pip install -vv < requirements.txt
script:
  - PYTHONMALLOC=malloc valgrind --show-leak-kinds=definite --log-file=/tmp/valgrind-output python -m pytest -rxXs -vv --valgrind --valgrind-log=/tmp/valgrind-output