language: python
dist: focal
addons:
  apt:
    packages:
      - cmake
      - valgrind
before_install:
  - python -m pip install --upgrade pip
install:
  - pip install -r requirements.txt -vv
script:
  - PYTHONMALLOC=malloc valgrind --show-leak-kinds=definite --log-file=/tmp/valgrind-output python -m pytest -s -vv --valgrind --valgrind-log=/tmp/valgrind-output