language: python
addons:
  apt:
    sources:
      - sourceline: 'deb https://apt.kitware.com/ubuntu/ xenial main'
      - key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
    packages:
      - cmake
install:
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_POSITION_INDEPENDENT_CODE=ON -Bbuild libs/libsignal-protocol-c
  - make -C build
  - pip install -r requirements.txt
  - python src/cffi/build.py
script:
  - PYTHONMALLOC=malloc valgrind --show-leak-kinds=definite --log-file=/tmp/valgrind-output python -m pytest -s -vv --valgrind --valgrind-log=/tmp/valgrind-output